name: Auto Rebase

on:
  push:
    branches: [ main ]

jobs:
  auto-rebase:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Rebase PRs on main update
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Get list of open PRs
          prs=$(gh pr list --json number,headRefName --state open --jq '.[] | "\(.number):\(.headRefName)"')
          
          for pr in $prs; do
            pr_number=$(echo $pr | cut -d: -f1)
            branch=$(echo $pr | cut -d: -f2)
            
            echo "Updating PR #$pr_number (branch: $branch)"
            
            # Fetch the PR branch
            git fetch origin $branch
            
            # Try to rebase the branch on main
            if git checkout $branch && git rebase origin/main; then
              git push --force-with-lease origin $branch
              gh pr comment $pr_number --body "✅ Automatically rebased onto latest main"
            else
              git rebase --abort
              gh pr comment $pr_number --body "⚠️ Could not automatically rebase onto main. Please resolve conflicts manually."
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  issues: write